import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const project = resolve(import.meta.dirname, '..');
const sourcePath = resolve(project, 'maps/verdant-rift.tmj');
const targetPath = resolve(project, 'src/game/content/maps/generated/verdantRift.ts');
const check = process.argv.includes('--check');

const property = (owner, name) => owner.properties?.find((candidate) => candidate.name === name)?.value;
const map = JSON.parse(await readFile(sourcePath, 'utf8'));
const navigation = map.layers.find((layer) => layer.name === 'Navigation' && layer.type === 'objectgroup');
const padLayer = map.layers.find((layer) => layer.name === 'Build Pads' && layer.type === 'objectgroup');
const route = navigation?.objects.find((object) => object.name === 'enemy-route' && Array.isArray(object.polyline));
const entrance = navigation?.objects.find((object) => object.name === 'entrance');
const gate = navigation?.objects.find((object) => object.name === 'gate');
if (!navigation || !padLayer || !route || !entrance || !gate) throw new Error('Map requires Navigation/enemy-route/entrance/gate and Build Pads layers.');

const points = route.polyline.map((point) => ({ x: route.x + point.x, y: route.y + point.y }));
const pads = padLayer.objects
  .map((object) => ({ index: Number(property(object, 'index')), x: object.x + object.width / 2, y: object.y + object.height / 2 }))
  .sort((a, b) => a.index - b.index);
if (points.length < 2) throw new Error('Enemy route must contain at least two points.');
if (pads.length < 1 || pads.some((pad, index) => pad.index !== index)) throw new Error('Build pad indices must be contiguous from zero.');
for (const [label, point] of [...points.map((point, index) => [`route ${index}`, point]), ...pads.map((point) => [`pad ${point.index}`, point])]) {
  if (!Number.isFinite(point.x) || !Number.isFinite(point.y)) throw new Error(`${label} has invalid coordinates.`);
  if (point.x < -map.width * 0.1 || point.x > map.width * 1.1 || point.y < -map.height * 0.1 || point.y > map.height * 1.1) throw new Error(`${label} is outside the supported authoring margin.`);
}

const formatPoint = ({ x, y }) => `{ x: ${Number(x.toFixed(2))}, y: ${Number(y.toFixed(2))} }`;
const rows = (items, width = 4) => Array.from({ length: Math.ceil(items.length / width) }, (_, index) => `      ${items.slice(index * width, index * width + width).map(formatPoint).join(', ')},`).join('\n');
const output = `import type { BattleMapDefinition } from '../types';

// Generated by \`pnpm map:sync\` from maps/verdant-rift.tmj. Do not hand-edit.
export const VERDANT_RIFT_MAP = {
  id: '${property(map, 'id')}',
  title: '${property(map, 'title')}',
  world: { width: ${map.width}, height: ${map.height} },
  backgroundAsset: '${property(map, 'backgroundAsset')}',
  route: {
    halfWidth: ${Number(property(route, 'halfWidth'))},
    centerline: [
${rows(points)}
    ],
  },
  buildPads: [
${rows(pads)}
  ],
  markers: {
    entrance: { x: ${entrance.x}, y: ${entrance.y}, label: '${property(entrance, 'label')}' },
    gate: { x: ${gate.x}, y: ${gate.y}, label: '${property(gate, 'label')}' },
  },
} as const satisfies BattleMapDefinition;
`;

if (check) {
  const current = await readFile(targetPath, 'utf8');
  if (current !== output) throw new Error('Generated map data is stale. Run `pnpm map:sync`.');
  console.log('Tiled map and runtime geometry are synchronized.');
} else {
  await writeFile(targetPath, output);
  console.log(`Updated ${targetPath}`);
}
